#theme: jekyll-theme-architect
# Site settings
title: lufeipeng blog
email: lufeipeng@gmail.com
author: John Otander
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl: ""
url: "网站url，如:http://lufeipeng.com"

# Build settings
markdown: kramdown
permalink: pretty
#每页文章数量
paginate: 6