#theme: jekyll-theme-architect
# Site settings
title: lufeipeng blog
email: lufeipeng@gmail.com
author: John Otander
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl: ""
url: "网站url，如:http://lufeipeng.com"


#Baidu analytics / 百度统计(异步的js码，注意使用异步版本的)
#baidu_analyze: 3908cbb144cf558ba6a823230d653fc22 

# Google analytics
google_analytics:UA-102705890-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: false
github_username:lufeipeng
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown: kramdown
permalink: pretty
#每页文章数量
paginate: 6